name: boilerplate
description: BKAV Camera.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+120

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  firebase_messaging: ^5.0.4
  webview_flutter: ^0.3.15+1
  flutter_secure_storage: ^3.3.5
  cupertino_icons: ^1.0.0
  shared_preferences: ^0.5.12+4
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  provider: ^4.3.3
  validators: ^2.0.1
  dio: 3.0.8
  flushbar: ^1.10.4
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject
      ref: 7c3cbf6
  sembast: ^2.4.8+1
  xxtea: ^2.0.3
  path_provider: ^1.6.27
  flutter_spinkit: ^4.1.2+1
  modal_bottom_sheet: ^1.0.0+1
  permission_handler: ^5.0.1+1
  flutter_datetime_picker: ^1.5.0
  intl: ^0.16.1
  typed_data: ^1.2.0
  smart_select: ^4.3.2
  flutter_widgets: ^0.1.12
  flutter_overlay_loader: ^0.0.2
  save_in_gallery:
    git: https://github.com/quanghd96/save_in_gallery.git
  toast: ^0.1.5
  photo_gallery:
    git: https://github.com/quanghd96/photo_gallery.git
  share: ^0.6.5+4
  photo_manager: ^0.6.0
  cached_network_image: ^2.5.0
  # fix version local auth for Android SDK 29
  local_auth: 0.6.1
  indexed_list_view: ^1.1.7
  flutter_xlider: ^3.4.0
  flutter_vlc_player:
    path: plugins/flutter_vlc_player/flutter_vlc_player
  pull_to_refresh: 1.6.3
  photo_view:
    path: plugins/photo_view

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.5.1
  build_runner: ^1.10.2
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.8.1
  mobx_codegen: ^1.1.2
  build_resolvers: ^1.3.11

flutter_icons:
  image_path: "assets/icons/ic_launcher.png"
  android: true
  ios: true


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
